### PR TITLE
Upgrade to PrestaShop 8.0

### LINKED ISSUE #70: Feature Request: Prestashop 8 support
We need to make sure that our module will work with the newly release Prestashop 8. Changes can be found here: https://devdocs.prestashop-project.org/8/modules/core-updates/8.0/

### PR DESCRIPTION
**Pull request by BitcoinMitchell**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | This MR upgrades the plugin to PHP 8 (or PHP 8.1) and PrestaShop 8.0. The amount of changes are minimal, but since we are bumping the base PrestaShop requirement (and PrestaShop being PHP 8/8.1 compatible) it would be a waste to not also update our PHP version
| Type?         | improvement
| BC breaks?    | yes
| Deprecations? | no
| Fixed ticket? | Fixes https://github.com/btcpayserver/prestashop-plugin/issues/70

---

This is currently a draft and testing version will be attached to this MR.

**Versions**

- 6.0.0.1: [btcpay.zip](https://github.com/btcpayserver/prestashop-plugin/files/10440206/btcpay.zip)
- 6.0.0.2: [btcpay.zip](https://github.com/btcpayserver/prestashop-plugin/files/10788277/btcpay.zip)
- 6.0.0.3: [btcpay.zip](https://github.com/btcpayserver/prestashop-plugin/files/12029891/btcpay.zip)

### CODE REVIEW

**Comment by BitcoinMitchell** [comment]
@powerpowera would you be able to test this? I've done some local testing and it looks good, but it would help if someone else could test it as well.

**Comment by powerpowera** [comment]
Page not found
The controller AdminConfigureBTCPay is missing or invalid.

I'm getting this when trying to update. 

Everything's fine when I'm using fresh local env.

**Comment by BitcoinMitchell** [comment]
> Page not found The controller AdminConfigureBTCPay is missing or invalid.
> 
> I'm getting this when trying to update.
> 
> Everything's fine when I'm using fresh local env.

Odd, thank you for the feedback! I'll try and figure out why that happens.

**Comment by BitcoinMitchell** [comment]
Resolved an issue with the upgrade script that might relate to the page error. Not 100% sure, but sharing it none-the-less. Will keep looking for other issues.

---

6.0.0.2: [btcpay.zip](https://github.com/btcpayserver/prestashop-plugin/files/10788277/btcpay.zip)

**Comment by powerpowera** [comment]
An exception has been thrown during the rendering of a template ("Unable to generate a URL for the named route "admin_btcpay_configure" as such route does not exist.").

**Comment by BitcoinMitchell** [comment]
> An exception has been thrown during the rendering of a template ("Unable to generate a URL for the named route "admin_btcpay_configure" as such route does not exist.").

Could you please provide any additional information? Was this on a fresh install? An upgraded installation? What page did you visit?

**Comment by ndeet** [comment]
Hey, maybe related, when I use your 6.0.0.2 zip above on Presta 8.0.4 and I click on configure after successful install I get:
> Page not found.
> The controller AdminConfigureBTCPay is missing or invalid.

Looked into config/routes.yaml and maybe the legacy controller mapping does not work anymore? Any idea?

When I go to bank transfer config I see the following in browser url:
https://prestashop.ddev.site/admin-dev/index.php?controller=AdminModules&configure=ps_wirepayment

BTCPay:
https://prestashop.ddev.site/admin-dev/index.php?controller=AdminConfigureBTCPay


In the error logs I see the below error, but seems to be unrelated and only triggered because of some PHP notice breaking some template or something like that.

```
[05-May-2023 13:54:10] WARNING: [pool www] child 1908 said into stderr: "NOTICE: PHP message: PHP Fatal error:  Uncaught ErrorException: Warning: Undefined property: Symfony\Component\VarDumper\Caster\CutStub::$cache_locking in /var/www/html/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php:737"
[05-May-2023 13:54:10] WARNING: [pool www] child 1908 said into stderr: "Stack trace:"
[05-May-2023 13:54:10] WARNING: [pool www] child 1908 said into stderr: "#0 [internal function]: Smarty_Internal_Template->__destruct()"
[05-May-2023 13:54:10] WARNING: [pool www] child 1908 said into stderr: "#1 {main}"
[05-May-2023 13:54:10] WARNING: [pool www] child 1908 said into stderr: "  thrown in /var/www/html/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php on line 737"
```

**Comment by BitcoinMitchell** [comment]
Hmmmmm, it would be weird if they break that compatibility, since most plugins I've seen can support Prestashop 1.7 and Prestashop 8. That said, would be worth looking into, thank you for the shout @ndeet.

The warning you see seems to be unrelated yeah.

**Comment by BitcoinMitchell** [comment]
We've done some more work @powerpowera, would you be willing to try this new version?

> 6.0.0.3: [btcpay.zip](https://github.com/btcpayserver/prestashop-plugin/files/12029891/btcpay.zip)

**Comment by powerpowera** [comment]
Sure thing, I'll keep you posted within few days. @BitcoinMitchell

**Comment by powerpowera** [comment]
So far all good! @BitcoinMitchell

**Comment by BitcoinMitchell** [comment]
> So far all good! @BitcoinMitchell

Glad to hear it. I'll merge this then and make it the new default version. Thank all for the help

**Pull request merged**
