### PR TITLE
Resolved callback issue (500 error: Kernel Container is not available)

### PR DESCRIPTION
**Pull request by BitcoinMitchell**
It seems that since 1.7.6 the Kernel must be initialized for callback URL's: https://github.com/PrestaShop/PrestaShop/issues/15503

So I've added the code that was posted (https://github.com/PrestaShop/PrestaShop/issues/15503#issuecomment-530800626) to the module and it resolved the issue for me.

### CODE REVIEW

**Comment by NicolasDorier** [comment]
hey @woutersamaey interested to look at prestashop or that's not your thing?

**Comment by woutersamaey** [comment]
Prestashop isn’t my thing, sorry. I’m purely focusing on Magento 😉

**Comment by BitcoinMitchell** [comment]
Is it safe to assume that this repository is pretty much dead then? Seeing as @olinkl is the only person maintaining it and currently inactive? 

If that's the case, I would recommend adding a warning to the README, as this module no longer works with the latest PrestaShop version because of this issue (without a working callback no order will ever be created)

**Comment by NicolasDorier** [comment]
@BitcoinMitchell since @olinkl disappeared, do you want to maintain it? I can give you the repo rights.

**Comment by BitcoinMitchell** [comment]
@NicolasDorier I wouldn't mind trying to maintain it, but I have very little experience with PrestaShop modules.

**Comment by NicolasDorier** [comment]
@BitcoinMitchell  I added you as admin of this repo (https://github.com/btcpayserver/prestashop-plugin/invitations). You may not have experience, but you can test and care about making it works, which is better than letting this repository rot and making it hard for you to improve.

**Comment by BitcoinMitchell** [comment]
@NicolasDorier That is very true. I'll make a `dev`-branch with all the PR's I've created and try and update the plugin structure to be more like the new 1.7.5.0 PretaShop modules before doing a final PR to merge it all.

**Comment by BitcoinMitchell** [comment]
I'll try and get the `dev` branch ready tonight. Closing this PR for now.

**Comment by pavlenex** [comment]
Just a follow up, I've actually met @olinkl in Berlin LNConf a few weeks ago, so he's certainly alive, don't worry. He's probably been a bit busy. I know for sure he's on BTCPay Slack, so you can def ping him there.

**Comment by BitcoinMitchell** [comment]
@pavlenex Glad to hear it and I'll make sure to join the Slack soon.

**Pull request closed without merging**
